Create Entities And Repositories, Minor SQL Fix
Dev-incubator/WebAutoparkRoman pull request #2
Opened 2021-04-07 07:35 UTC by UNDogMan

2021-04-07 14:54 UTC, dbogdan2000 commented on WebAutopark.DataAccess/Repository/OrderPartRepository.cs
> +            return connection.ExecuteAsync("insert into OrdersPartsvalues(@PartID, @OrderID, @PartCount); ", item);
Leave some space between "OrdersParts" and "values"

2021-04-07 14:56 UTC, dbogdan2000 commented on WebAutopark.DataAccess/Repository/OrderPartRepository.cs
> +            return connection.ExecuteAsync("insert into OrdersPartsvalues(@PartID, @OrderID, @PartCount); ", item);
Leave some space between "OrdersParts" and "values".

2021-04-07 15:42 UTC, dbogdan2000 approved these changes

2021-04-07 19:37 UTC, PushMeNow requested changes
Hi dude!)
I did some comments. Let me know if any questions.

2021-04-07 19:37 UTC, PushMeNow commented on WebAutopark.DataAccess/Repository/Base/RepositoryConnection.cs
> +    public abstract class RepositoryConnection : IDisposable, IAsyncDisposable
RepositoryConnection is bad name for me because I don't realize goals of the class. I think it will be better to name it like Repository or RepositoryBase. And one more thing just think you will need to move another common logic in this class. In the case we cannot names this class like RepositoryConnection because it will have other logic too.

2021-04-07 19:37 UTC, PushMeNow commented on WebAutopark.DataAccess/Repository/Base/RepositoryConnection.cs
> +        protected RepositoryConnection(string connectionString)
Could you write provider class (example ConnectionProvider and IConnectionProvider to include it in IoC). This class will have method to return connection string.

2021-04-11 10:02 UTC, PushMeNow requested changes
Hi!
I didn't see some inconsistency between your repositories and SQL code. So I have added comments in this review. Let me know if any questions.

2021-04-11 20:40 UTC, PushMeNow approved these changes
Approved

2021-04-11 20:40 UTC, merged