Complete BLL
Dev-incubator/WebAutoparkRoman pull request #4
Opened 2021-04-13 20:16 UTC by UNDogMan

2021-04-14 20:57 UTC, PushMeNow requested changes
Hi man!
I made some comments for you. Let me know if any questions.

2021-04-14 20:57 UTC, PushMeNow commented on WebAutopark.BusinessLogic/Services/OrderService.cs
> +            return repository.Create(mapper.Map<Order>(item)); ;
Excess colon

2021-04-14 20:57 UTC, PushMeNow commented on WebAutopark.BusinessLogic/Services/VehicleService.cs
> +        public async Task<float> GetTaxPerMount(VehicleDTO vehicle)
I don't see async operations here. Let's move logic of the method in helper Calculator

2021-04-14 20:57 UTC, PushMeNow commented on WebAutopark.BusinessLogic/Services/VehicleService.cs
> +            return vehicle.Weight * WeightCoefficient + type.TaxCoefficient * BaseTax + MinTax;
Let's move logic of this line in helper Calculator

2021-04-14 20:57 UTC, PushMeNow commented on WebAutopark.BusinessLogic/Services/VehicleService.cs
> +        private const int MinTax = 5;
I don't see the reason to create global constant here. We will not use them anywhere. Better create local constants.

2021-04-16 19:31 UTC, dbogdan2000 approved these changes

2021-04-18 15:23 UTC, PushMeNow approved these changes
Approved

2021-04-18 15:23 UTC, merged